import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;

import org.bukkit.Material;

/**
 * Offline inventory of the legacy "id:data" block pairs used by the building templates (*.def).
 *
 * Template line format: x:y:z,id:data[,extra...]   (first line: sizeX;sizeY;sizeZ)
 *
 * Usage (see tools/scan-templates.sh):
 *   ScanTemplates <templatesDir> --write <baselineFile>    write the current inventory
 *   ScanTemplates <templatesDir> --check <baselineFile>    fail when the inventory differs from the baseline
 *
 * Why: when the server moves past 1.12 the numeric ids stop existing, so every pair has to be mapped to a
 * modern block. This baseline is the list that mapping has to cover; --check makes a new template that
 * introduces an unmapped pair visible before it reaches a server.
 */
public class ScanTemplates {

	public static void main(String[] args) throws IOException {
		if (args.length != 3 || !(args[1].equals("--write") || args[1].equals("--check"))) {
			System.err.println("usage: ScanTemplates <templatesDir> --write|--check <baselineFile>");
			System.exit(2);
		}

		Path root = Paths.get(args[0]);
		Path baseline = Paths.get(args[2]);

		Map<String, Long> pairs = new TreeMap<>((a, b) -> {
			String[] x = a.split(":");
			String[] y = b.split(":");
			int c = Integer.compare(Integer.parseInt(x[0]), Integer.parseInt(y[0]));
			return c != 0 ? c : Integer.compare(Integer.parseInt(x[1]), Integer.parseInt(y[1]));
		});

		long files = 0, lines = 0, extra = 0, outOfBounds = 0, badId = 0, badData = 0, malformed = 0;

		List<Path> defs = new ArrayList<>();
		try (Stream<Path> s = Files.walk(root)) {
			s.filter(p -> p.toString().endsWith(".def")).sorted().forEach(defs::add);
		}

		for (Path def : defs) {
			files++;
			try (BufferedReader r = Files.newBufferedReader(def, StandardCharsets.ISO_8859_1)) {
				String header = r.readLine();
				if (header == null) {
					malformed++;
					continue;
				}
				String[] size = header.trim().split(";");
				int sx = Integer.parseInt(size[0]), sy = Integer.parseInt(size[1]), sz = Integer.parseInt(size[2]);

				String line;
				while ((line = r.readLine()) != null) {
					String[] f = line.split(",", -1);
					if (f.length < 2) {
						malformed++;
						continue;
					}
					String[] loc = f[0].split(":");
					String[] type = f[1].split(":");
					if (loc.length != 3 || type.length != 2) {
						malformed++;
						continue;
					}
					int x = Integer.parseInt(loc[0]), y = Integer.parseInt(loc[1]), z = Integer.parseInt(loc[2]);
					int id = Integer.parseInt(type[0]), data = Integer.parseInt(type[1]);

					if (x < 0 || x >= sx || y < 0 || y >= sy || z < 0 || z >= sz) {
						outOfBounds++;
					}
					if (id < 0 || id > 255) {
						badId++;
					}
					if (data < 0 || data > 15) {
						badData++;
					}
					if (f.length > 2) {
						extra++;
					}
					lines++;
					pairs.merge(id + ":" + data, 1L, Long::sum);
				}
			} catch (RuntimeException e) {
				System.err.println("cannot parse " + def + ": " + e);
				malformed++;
			}
		}

		List<String> out = new ArrayList<>();
		out.add("# Legacy block pairs used by civcraft_data/templates (id:data, line count, 1.12.2 Material)");
		out.add("# generated by tools/ScanTemplates.java - do not edit by hand");
		out.add("# files=" + files + " blockLines=" + lines + " commandLines=" + extra + " distinctPairs=" + pairs.size());
		long unknown = 0;
		for (Map.Entry<String, Long> e : pairs.entrySet()) {
			int id = Integer.parseInt(e.getKey().split(":")[0]);
			@SuppressWarnings("deprecation")
			Material m = Material.getMaterial(id);
			if (m == null) {
				unknown++;
			}
			out.add(e.getKey() + " " + e.getValue() + " " + (m == null ? "UNKNOWN" : m.name()));
		}

		System.out.println("files=" + files + " blockLines=" + lines + " commandLines=" + extra
				+ " distinctPairs=" + pairs.size() + " outOfBounds=" + outOfBounds + " badId=" + badId
				+ " badData=" + badData + " malformed=" + malformed + " unknownMaterial=" + unknown);

		boolean problems = outOfBounds + badId + badData + malformed + unknown > 0;

		if (args[1].equals("--write")) {
			Files.write(baseline, out, StandardCharsets.UTF_8);
			System.out.println("baseline written to " + baseline);
			System.exit(problems ? 1 : 0);
		}

		List<String> expected = Files.readAllLines(baseline, StandardCharsets.UTF_8);
		// Compare pair sets only: line counts change whenever a template is edited.
		java.util.Set<String> now = new java.util.TreeSet<>(), then = new java.util.TreeSet<>();
		for (String l : out) {
			if (!l.startsWith("#")) {
				now.add(l.split(" ")[0]);
			}
		}
		for (String l : expected) {
			if (!l.startsWith("#")) {
				then.add(l.split(" ")[0]);
			}
		}
		java.util.Set<String> added = new java.util.TreeSet<>(now);
		added.removeAll(then);
		java.util.Set<String> removed = new java.util.TreeSet<>(then);
		removed.removeAll(now);
		if (!added.isEmpty()) {
			System.out.println("new pairs not in baseline: " + added);
		}
		if (!removed.isEmpty()) {
			System.out.println("pairs no longer used: " + removed);
		}
		System.exit(problems || !added.isEmpty() ? 1 : 0);
	}
}
